title = 'Hugo-BS Temp'

[params]
    primEmail = "info@example.com"
    primPhone = "(123) 456-7890"

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
         unsafe = true
